#!/usr/bin/env bash
set -eux
set -o pipefail

DOTFILES_PATH="$HOME/plexiform/dotfiles"

# install spacemacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
cp ${DOTFILES_PATH}/spacemacs ~/.spacemacs

# install gitconfig
cp ${DOTFILES_PATH}/gitconfig ~/.gitconfig

# install lein and boot
mkdir ~/bin
cd ~/bin

curl -fsSLo lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein \
    && chmod 755 lein
curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh \
    && chmod 755 boot

cd ~/
git clone https://github.com/grzm/meetup-collab.git

cat <<"EOF" >> ~/.profile
# add plexiform/bin to path
PATH="$HOME/plexiform/bin:$PATH"
EOF
